version: '3.7'

services:
  db:
    image: postgis/postgis:13-3.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    command:
      postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_locks_per_transaction=1000
  flask:
    image: climbing-app
    build:
      context: .
      dockerfile: devops/flask.dockerfile
    depends_on:
      - db
    volumes:
      - .:/climbing
    env_file:
      - devops/.env.localhost
    ports:
      - 8000:8000
    command:
      - python
      - -m
      - app

volumes:
  db:


networks:
  default:
    name: local
